server:
    port: 10081
spring: 
    profiles:
        active: product 
    datasource: 
        url: jdbc:mysql://localhost:3306/web-sample?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        
